version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: threads-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: threads
       POSTGRES_DB: threads

volumes:
  postgres_data: